name: mixpanel_flutter_cloned
description: Official Flutter Tracking SDK for Mixpanel Analytics developed and maintained by Mixpanel, Inc.
version: 2.3.1
homepage: https://mixpanel.com
repository: https://github.com/genteel25/mixpanel-flutter_cloned
issue_tracker: https://github.com/mixpanel/mixpanel-flutter/issues
documentation: https://developer.mixpanel.com/docs/flutter

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ">=0.6.0 <0.8.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/mixpanel.js

  plugin:
    platforms:
      android:
        package: com.genteel25.mixpanel_flutter_cloned
        pluginClass: MixpanelFlutterPlugin
      ios:
        pluginClass: MixpanelFlutterPlugin
      web:
        pluginClass: MixpanelFlutterPlugin
        fileName: mixpanel_flutter_web.dart
